# Generated by Django 4.2.5 on 2023-11-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='opinion',
            field=models.TextField(null=True),
        ),
    ]
