# Generated by Django 4.2.5 on 2023-12-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_userquestion_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='opinion',
            field=models.TextField(default=''),
        ),
    ]
