# Generated by Django 4.2.5 on 2023-12-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
