# Generated by Django 4.2.5 on 2023-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_genre_alter_review_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.IntegerField(),
        ),
    ]
