# Generated by Django 4.2.5 on 2023-12-04 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_remove_book_genre'),
        ('review', '0003_alter_review_category_alter_review_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='scrap_count',
        ),
        migrations.AlterField(
            model_name='review',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reviewscrap',
            name='scrap',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.review')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserReview',
                'managed': True,
            },
        ),
    ]
