# Generated by Django 4.2.5 on 2023-12-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_review_like_count_remove_review_scrap_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='comment',
            new_name='content',
        ),
    ]
