# Generated by Django 4.2.5 on 2023-12-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_rename_comment_reviewcomment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='content',
            new_name='comment',
        ),
    ]
