# Generated by Django 4.2.5 on 2023-11-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_userbook_content_remove_userbook_disclosure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.IntegerField(),
        ),
    ]
