# Generated by Django 4.2.5 on 2023-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question_id',
            field=models.IntegerField(default=9),
        ),
    ]
