# Generated by Django 4.2.5 on 2023-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notification_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
